# Generated by Django 3.1.3 on 2021-01-21 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_removed_unnecessary_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularuserprofile',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
