# Generated by Django 3.0.7 on 2020-08-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_blank_param_to_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('regular_user', 'Regular'), ('psychologist_user', 'Psychologist'), ('admin_user', 'Admin')], max_length=50),
        ),
    ]
