version: '3.8'

services:
   db:
     ports:
       - "5432:5432"
     image: postgres:12-alpine
     env_file: .env-db
   redis:
     ports:
       - "6379:6379"
     image: redis:6-alpine
   web:
     build:
       context: .
     command: gunicorn --bind 0.0.0.0:8000 psy_time.wsgi
     env_file: .env
     volumes:
       - .:/psy_time
     ports:
       - "8000:8000"
     depends_on:
       - db