version: '3.8'

services:
   db:
     ports:
       - "127.0.0.1:5432:5432"
     image: postgres:12-alpine
     env_file: .env-db
   web:
     build:
       context: .
       dockerfile: dev.Dockerfile
     command: python3 manage.py runserver 127.0.0.1:8000
     env_file: .env
     volumes:
       - .:/psy_time
     ports:
       - "127.0.0.1:8000:8000"
     depends_on:
       - db