# Generated by Django 3.1.1 on 2020-10-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('theme', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('I', 'In the process'), ('C', 'Closed')], default='P', max_length=50)),
            ],
        ),
    ]
