# Generated by Django 3.0.7 on 2020-08-10 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologistUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50)),
                ('avatar', models.ImageField(null=False, default='avatars/psy_avatar.jpg', upload_to='avatars')),
                ('birth_date', models.DateField()),
                ('about', models.TextField()),
                ('work_experience', models.TextField()),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('city',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.City')),
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.PsychologistUser')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('profile',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='psychologists.PsychologistUserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='PsychologistApproach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('profiles',
                 models.ManyToManyField(related_name='approaches', to='psychologists.PsychologistUserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='PsychologistEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('profiles',
                 models.ManyToManyField(related_name='educations', to='psychologists.PsychologistUserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='PsychologistLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('profiles',
                 models.ManyToManyField(related_name='languages', to='psychologists.PsychologistUserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='PsychologistSecondaryEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('profiles',
                 models.ManyToManyField(related_name='secondary_educations',
                                        to='psychologists.PsychologistUserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='PsychologistSpecialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('profiles',
                 models.ManyToManyField(related_name='specializations', to='psychologists.PsychologistUserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='PsychologistStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('profiles',
                 models.ManyToManyField(related_name='statuses', to='psychologists.PsychologistUserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='PsychologistTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('profiles',
                 models.ManyToManyField(related_name='themes', to='psychologists.PsychologistUserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='PsychologistWorkFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('profiles',
                 models.ManyToManyField(related_name='formats', to='psychologists.PsychologistUserProfile')),
            ],
        ),
    ]
