# Generated by Django 3.1.3 on 2020-11-14 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_removed_unnecessary_fields'),
        ('psychologists', '0002_psy_related_models_redesign'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologistReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.regularuserprofile')),
                ('psychologist_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psy_reviews', to='psychologists.psychologistuserprofile')),
            ],
        ),
    ]
