# Generated by Django 3.1.1 on 2020-10-16 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201016_1059'),
        ('psychologists', '0002_psy_related_models_redesign'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologistReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.regularuser')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psy_reviews', to='users.psychologistuser')),
            ],
        ),
    ]
