# Generated by Django 3.1.1 on 2020-10-15 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0002_psy_related_models_redesign'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologistReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='psychologists.psychologistuserprofile')),
            ],
        ),
    ]
