# Generated by Django 3.1.3 on 2021-01-21 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0003_psy_reviews_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='psychologistreview',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='psychologistuserprofile',
            name='about',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(50)]),
        ),
        migrations.AlterField(
            model_name='psychologistuserprofile',
            name='duration',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='psychologistuserprofile',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='psychologistuserprofile',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='psychologistuserprofile',
            name='work_experience',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(50)]),
        ),
    ]
