# Generated by Django 3.0.7 on 2020-08-10 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.AdminUser'),
        ),
    ]
