# Generated by Django 3.1.3 on 2020-11-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('name', 'country'),
                                               name='the city must be unique within the country'),
        ),
        migrations.AddConstraint(
            model_name='timezone',
            constraint=models.UniqueConstraint(fields=('name', 'country'),
                                               name='the timezone must be unique within the country'),
        ),
    ]
