# Generated by Django 3.0.7 on 2020-08-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20200810_1143'),
        ('locations', '0002_location_name_unique'),
    ]

    operations = [
    ]
