# Generated by Django 3.1.3 on 2021-01-21 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_uniquenesses_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timezone',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='timezone',
            name='offset',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
