# Generated by Django 3.1.3 on 2020-11-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_city_unique_within_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
